### ISSUE TITLE
Missing class, methods documentation

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/dwave-tabu#43]
https://docs.ocean.dwavesys.com/projects/tabu/en/latest/reference/sampler.html is empty
Used to show class & methods. Did you break the path?

**Comment by randomir** [comment]
Interesting, the [stable version](https://docs.ocean.dwavesys.com/projects/tabu/en/stable/reference/sampler.html) works. And my local build is correct. Need to investigate.

**Comment by randomir** [comment]
Got it. The bug was introduced in e3b590de.

If `tabu.tabu_search` file is not properly mocked while building docs with:
```
autodoc_mock_imports = ["tabu.tabu_search"]
```
`TabuSampler` import fails (and the docstring is not compiled).

The reason we need to mock it is because otherwise we would need to build it. And to build it, we need `swig`, which is not available on RtD (see #25). The only alternative IIRC is to roll out our docker build container.

**Comment by randomir** [comment]
Closed by #46.
